workflows:
  flutter_webview:
    name: Flutter WebView App
    environment:
      flutter: stable
      xcode: default      # required even if you don't build iOS
      cocoapods: default  # required even if you don't build iOS
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
